### PR TITLE
Add Fasih Rehman to AWS

### PR DESCRIPTION
**Pull request by jakemulley**
This PR adds an IAM user for Fasih Rehman.

### CODE REVIEW

**Review by ezman — COMMENTED** [review]
My keybase id : ‘fasih_rehman’.

**Review by seanprivett — APPROVED** [review]

**Review by donmasters — APPROVED** [review]
LGTM

**Comment by jakemulley** [comment]
Added @ezman's keybase ID 👍🏼

**Review by davidkelliott — APPROVED** [review]
👍

**Pull request merged**
